// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/zdai.proto

package zdai

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "go-micro.dev/v5/client"
	server "go-micro.dev/v5/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Zdai service

type ZdaiService interface {
	HealthCall(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error)
	ListRunsCall(ctx context.Context, in *ListRunsRequest, opts ...client.CallOption) (*ListRunsResponse, error)
	GetRunCall(ctx context.Context, in *GetRunRequest, opts ...client.CallOption) (*GetRunResponse, error)
	DispatchCall(ctx context.Context, in *DispatchRequest, opts ...client.CallOption) (*DispatchResponse, error)
	AgentRunCall(ctx context.Context, in *AgentRunRequest, opts ...client.CallOption) (*AgentRunResponse, error)
	RegisterEmailThreadCall(ctx context.Context, in *RegisterEmailThreadRequest, opts ...client.CallOption) (*RegisterEmailThreadResponse, error)
}

type zdaiService struct {
	c    client.Client
	name string
}

func NewZdaiService(name string, c client.Client) ZdaiService {
	return &zdaiService{
		c:    c,
		name: name,
	}
}

func (c *zdaiService) HealthCall(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error) {
	req := c.c.NewRequest(c.name, "Zdai.HealthCall", in)
	out := new(HealthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zdaiService) ListRunsCall(ctx context.Context, in *ListRunsRequest, opts ...client.CallOption) (*ListRunsResponse, error) {
	req := c.c.NewRequest(c.name, "Zdai.ListRunsCall", in)
	out := new(ListRunsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zdaiService) GetRunCall(ctx context.Context, in *GetRunRequest, opts ...client.CallOption) (*GetRunResponse, error) {
	req := c.c.NewRequest(c.name, "Zdai.GetRunCall", in)
	out := new(GetRunResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zdaiService) DispatchCall(ctx context.Context, in *DispatchRequest, opts ...client.CallOption) (*DispatchResponse, error) {
	req := c.c.NewRequest(c.name, "Zdai.DispatchCall", in)
	out := new(DispatchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zdaiService) AgentRunCall(ctx context.Context, in *AgentRunRequest, opts ...client.CallOption) (*AgentRunResponse, error) {
	req := c.c.NewRequest(c.name, "Zdai.AgentRunCall", in)
	out := new(AgentRunResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zdaiService) RegisterEmailThreadCall(ctx context.Context, in *RegisterEmailThreadRequest, opts ...client.CallOption) (*RegisterEmailThreadResponse, error) {
	req := c.c.NewRequest(c.name, "Zdai.RegisterEmailThreadCall", in)
	out := new(RegisterEmailThreadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Zdai service

type ZdaiHandler interface {
	HealthCall(context.Context, *HealthRequest, *HealthResponse) error
	ListRunsCall(context.Context, *ListRunsRequest, *ListRunsResponse) error
	GetRunCall(context.Context, *GetRunRequest, *GetRunResponse) error
	DispatchCall(context.Context, *DispatchRequest, *DispatchResponse) error
	AgentRunCall(context.Context, *AgentRunRequest, *AgentRunResponse) error
	RegisterEmailThreadCall(context.Context, *RegisterEmailThreadRequest, *RegisterEmailThreadResponse) error
}

func RegisterZdaiHandler(s server.Server, hdlr ZdaiHandler, opts ...server.HandlerOption) error {
	type zdai interface {
		HealthCall(ctx context.Context, in *HealthRequest, out *HealthResponse) error
		ListRunsCall(ctx context.Context, in *ListRunsRequest, out *ListRunsResponse) error
		GetRunCall(ctx context.Context, in *GetRunRequest, out *GetRunResponse) error
		DispatchCall(ctx context.Context, in *DispatchRequest, out *DispatchResponse) error
		AgentRunCall(ctx context.Context, in *AgentRunRequest, out *AgentRunResponse) error
		RegisterEmailThreadCall(ctx context.Context, in *RegisterEmailThreadRequest, out *RegisterEmailThreadResponse) error
	}
	type Zdai struct {
		zdai
	}
	h := &zdaiHandler{hdlr}
	return s.Handle(s.NewHandler(&Zdai{h}, opts...))
}

type zdaiHandler struct {
	ZdaiHandler
}

func (h *zdaiHandler) HealthCall(ctx context.Context, in *HealthRequest, out *HealthResponse) error {
	return h.ZdaiHandler.HealthCall(ctx, in, out)
}

func (h *zdaiHandler) ListRunsCall(ctx context.Context, in *ListRunsRequest, out *ListRunsResponse) error {
	return h.ZdaiHandler.ListRunsCall(ctx, in, out)
}

func (h *zdaiHandler) GetRunCall(ctx context.Context, in *GetRunRequest, out *GetRunResponse) error {
	return h.ZdaiHandler.GetRunCall(ctx, in, out)
}

func (h *zdaiHandler) DispatchCall(ctx context.Context, in *DispatchRequest, out *DispatchResponse) error {
	return h.ZdaiHandler.DispatchCall(ctx, in, out)
}

func (h *zdaiHandler) AgentRunCall(ctx context.Context, in *AgentRunRequest, out *AgentRunResponse) error {
	return h.ZdaiHandler.AgentRunCall(ctx, in, out)
}

func (h *zdaiHandler) RegisterEmailThreadCall(ctx context.Context, in *RegisterEmailThreadRequest, out *RegisterEmailThreadResponse) error {
	return h.ZdaiHandler.RegisterEmailThreadCall(ctx, in, out)
}
