when:
  - event: push
    branch: [main]

depends_on:
  - test
  - build-amd64

matrix:
  platform:
    - linux/amd64

labels:
  platform: ${platform}

steps:
  - name: deploy
    image: docker.io/loq9/drone-nomad
    privileged: true
    environment:
      reg_user:
        from_secret: docker_user
      reg_pass:
        from_secret: docker_pass
      approle_id:
        from_secret: zdai_id
      approle_secret:
        from_secret: zdai_secret
      vault_address:
        from_secret: vault_address
      github_token:
        from_secret: github_token
      PLUGIN_ADDR: http://nomad.service.consul:4646
      PLUGIN_TEMPLATE: nomad/zdai.hcl
      DRONE_COMMIT_SHA: ${CI_COMMIT_SHA:0:8}
